---
# Source: docker-registry/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: local-secret
  namespace: registry
  labels:
    app: local
    chart: docker-registry-2.1.0
    heritage: Helm
    release: local
type: Opaque
data:
  haSharedSecret: "Z2dkQ2R2UzB4eGNDYzlJQw=="
  proxyUsername: ""
  proxyPassword: ""
