apiVersion: v1
kind: Namespace
metadata:
  name: registry
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-ca-issuer
  namespace: registry
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ca-cert
  namespace: registry
spec:
  isCA: true
  commonName: registry-selfsigned
  secretName: ca-cert
  issuerRef:
    name: selfsigned-ca-issuer
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: registry
spec:
  ca:
    secretName: ca-cert
