# This is used with https://github.com/twuni/docker-registry.helm to generate the registry config.
# Run:
#   helm repo add twuni https://helm.twun.io
#   helm template local twuni/docker-registry -f .\registry-chart-values.yml --output-dir helm-out
#   mv helm-out/docker-registry/templates registry
persistence:
  enabled: true
  size: 200G
namespace: registry
# tlsSecretName: registry-cert
# service:
#   port: 443
nameOverride: local
ingress:
  enabled: true
  className: ""  # Use cluster default
  annotations:
    cert-manager.io/issuer: selfsigned-issuer
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
# ingress:
#   enabled: true
#   className: ""  # Use cluster default
#   annotations:
#     cert-manager.io/issuer: local-registry-ca
#   hosts:
#   - local.registry.svc
#   tls:
#   - hosts:
#     - local.registry.svc
#     secretName: registry-cert
