# This is used with https://github.com/twuni/docker-registry.helm to generate the registry config.
# Run:
#   helm repo add twuni https://helm.twun.io
#   helm template local twuni/docker-registry -f .\registry-chart-values.yml --output-dir helm-out
#   mv helm-out/docker-registry/templates registry
persistence:
  enabled: true
  size: 200G
namespace: registry
nameOverride: local
configData:
  validation:
    disabled: true  # Needed to accept imgpkg copies
ingress:
  enabled: true
  className: ""  # Use cluster default
  annotations:
    cert-manager.io/issuer: selfsigned-issuer
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
